meta_product_name: "Laura Hardy-Dessources"
meta_title: "Laura Hardy-Dessources - Front-end developer Junior"
meta_description: "Hello ğŸ‘‹ğŸ¾ Je m'appelle Laura Hardy-Dessources et je suis Front-End dÃ©veloppeuse Junior et webdesigner."
meta_image: "macbook_portfolio.png" # should exist in `app/assets/images/`
twitter_account: "@lhdesign972"   # required for Twitter Cards
